name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: build
        run: ./gradlew build --stacktrace --no-daemon

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: betterbarriers-artifacts
          path: build/libs/
